### PR TITLE
[PR] Initial `Supabase` `Flutter` demo app 🚀 

### PR DESCRIPTION
**Pull request by LuchoTurtle**
This PR creates an initial implementation of integrating authentication with `supabase` with a Flutter application.

It's still very much in progress, as I didn't have much time to spend on this as I wanted to (packing stuff and getting prepped before the weekend). 

I wanted to use a pre-existent Flutter app that we had and I wanted to go for a `todo` app since it's closest to our `mvp`. However, in `dwyl/flutter-todo-list-tutorial`, my PR https://github.com/dwyl/flutter-todo-list-tutorial/pull/28 is not yet merged so I had to try to choose a specific version that *didn't have* any API calls (wouldn't make sense to have users in this repo install Elixir and Phoenix) so that took some trial and error going through commit history.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
image

Following the tutorial, the user has to receive a magic link and click on the e-mail confirmation link to access the app. It makes sense but for a tutorial, a simple username/email and password make more sense. I'm going to refactor this so the user signs in with normal credentials.

**Comment by LuchoTurtle** [comment]
This PR is technically done. Not going to submit for review because I want to review the README first for any typos.

**Comment by LuchoTurtle** [comment]
The link from the `supabase` Flutter tutorial, as explained in the previous comment,  uses authentication via magic link that has to be confirmed through e-mail confirmation.

https://supabase.com/docs/guides/getting-started/tutorials/with-flutter

This demo greatly deviates from this and uses e-mail/password auth.

**Comment by nelsonic** [comment]
@LuchoTurtle going to try and take a look at this today. 👌

**Comment by nelsonic** [comment]
```sh
flutter test --coverage
```

Get:

```sh
Test directory "test" not found.
```

No `/test` directory in the branch:
https://github.com/dwyl/supabase-flutter-demo/tree/initial-implementation
image

But `flutter analyze` returns:
```sh
Analyzing supabase-flutter-demo...                                      
No issues found! (ran in 1.1s)
```

**Comment by nelsonic** [comment]
Getting "unexpected error occurred" ... 
flutter-supabase-unexpected-error

No output in the debugger. 🤷‍♂️ 

@LuchoTurtle please walk me through this after Standup tomorrow morning. 🙏

**Comment by LuchoTurtle** [comment]
I think this was because the project was paused.

Screenshot 2023-02-15 at 09 03 12

Supabase pauses the project automatically if there's no activity for a while.
Perhaps we should have people create an account and input their own `anon` key.

**Comment by nelsonic** [comment]
Indeed. "Restoration in progress ... "
image

**Comment by nelsonic** [comment]
That took a `while` ... ⏳ 
Glad I wasn't holding my breath.

image

Wonder why they haven't figured out how to do this a _lot_ faster. 🤷‍♂️ 
Also, with their level of funding https://techcrunch.com/2022/05/10/supabase-raises-80m-series-b-for-its-open-source-firebase-alternative/ _surely_ they don't _need_ to be doing this? ⏳

**Review by nelsonic — CHANGES_REQUESTED** [review]
Please add tests. see: https://github.com/dwyl/supabase-flutter-demo/pull/2#issuecomment-1430711391
Even basic ones are better than nothing. 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle from our conversation on Standup, it appears that testing the `Supabase` functions is not easy as there is no `Mock` library for the "side-effects" (i.e. anything that calls the `Supabase` `API` or `Client` library ...)
So adding _comprehensive_ tests will likely take a _very_ long time because we would need to `Mock` each call.

So I suggest that you just find _something_ you can test in this demo just so that there is a `/test` folder. 
And then we can merge the PR. 👌

**Comment by nelsonic** [comment]
For clarity: this is the one instance in which having 100% test coverage is unfeasible in terms of the time we have available. (we already exhausted the "1 Day" allocated to the spike)

**Comment by nelsonic** [comment]
Please spend no more than **`T2h`** on adding the tests. If you can only get a certain percentage of coverage. Then just drop a line in the `README.md` clarifying that mocking the `Supabase` client is not currently available and "beyond the scope" of this quick demo. 👌

**Comment by LuchoTurtle** [comment]
The *only* way to test anything was to mock the `supabase` variable, as it was immediately accessed on startup.,
I did this and added a couple of tests after battling with `Mockito` to properly mock the class and stubbing the appropriate fields.
I eventually got over it but I don't have more time to add more tests to complete the rest of the coverage.

image

**Comment by LuchoTurtle** [comment]
CI should now be properly working 👍

**Review by nelsonic — APPROVED** [review]
Nice one @LuchoTurtle thanks for adding the tests. ✅

**Pull request merged**
